/**
 * NG Phoneme Data — 78 phonemes marked as NG (bad quality) in manual QA.
 * Used by regenerate-ng-phonemes.ts for Gemini 2.5 Flash TTS regeneration.
 */

export interface NgPhonemeEntry {
  id: string;
  type: 'core' | 'onset' | 'rime';
  phoneme: string;
  ipa: string;
  exampleWords: string[];
  soundPosition: string;
  category: string;
}

export const ngPhonemes: NgPhonemeEntry[] = [
  // ═══════════════════════════════════════
  // CORE (12) — isolated vowel/consonant sounds
  // ═══════════════════════════════════════
  {
    id: 'core_ar',
    type: 'core',
    phoneme: 'ar',
    ipa: 'ɑːɹ',
    exampleWords: ['car', 'star', 'farm'],
    soundPosition: 'R-controlled vowel, as in the middle of "car" or "farm"',
    category: 'r-controlled vowel',
  },
  {
    id: 'core_aw',
    type: 'core',
    phoneme: 'aw',
    ipa: 'ɔː',
    exampleWords: ['saw', 'paw', 'draw'],
    soundPosition: 'Open back rounded vowel, as in the end of "saw" or "paw"',
    category: 'diphthong/long vowel',
  },
  {
    id: 'core_ay',
    type: 'core',
    phoneme: 'ay',
    ipa: 'eɪ',
    exampleWords: ['say', 'play', 'day'],
    soundPosition: 'Long A diphthong, as in the end of "say" or "play"',
    category: 'diphthong',
  },
  {
    id: 'core_ee',
    type: 'core',
    phoneme: 'ee',
    ipa: 'iː',
    exampleWords: ['see', 'tree', 'bee'],
    soundPosition: 'Long E vowel, as in "see" or "bee"',
    category: 'long vowel',
  },
  {
    id: 'core_eh',
    type: 'core',
    phoneme: 'eh',
    ipa: 'ɛ',
    exampleWords: ['bed', 'red', 'pen'],
    soundPosition: 'Short E vowel, as in the middle of "bed" or "red"',
    category: 'short vowel',
  },
  {
    id: 'core_er',
    type: 'core',
    phoneme: 'er',
    ipa: 'ɜːɹ',
    exampleWords: ['her', 'bird', 'turn'],
    soundPosition: 'R-controlled vowel, as in "her", "bird", or "turn"',
    category: 'r-controlled vowel',
  },
  {
    id: 'core_ih',
    type: 'core',
    phoneme: 'ih',
    ipa: 'ɪ',
    exampleWords: ['sit', 'big', 'fish'],
    soundPosition: 'Short I vowel, as in the middle of "sit" or "big"',
    category: 'short vowel',
  },
  {
    id: 'core_j',
    type: 'core',
    phoneme: 'j',
    ipa: 'dʒ',
    exampleWords: ['jam', 'jump', 'jug'],
    soundPosition: 'Voiced affricate consonant, as at the start of "jam" or "jump"',
    category: 'affricate',
  },
  {
    id: 'core_ng',
    type: 'core',
    phoneme: 'ng',
    ipa: 'ŋ',
    exampleWords: ['ring', 'sing', 'king'],
    soundPosition: 'Velar nasal consonant, as at the end of "ring" or "sing"',
    category: 'nasal',
  },
  {
    id: 'core_th',
    type: 'core',
    phoneme: 'th',
    ipa: 'θ',
    exampleWords: ['thin', 'three', 'think'],
    soundPosition: 'Voiceless dental fricative, as at the start of "thin" or "three"',
    category: 'fricative',
  },
  {
    id: 'core_th_v',
    type: 'core',
    phoneme: 'th',
    ipa: 'ð',
    exampleWords: ['the', 'this', 'that'],
    soundPosition: 'Voiced dental fricative, as at the start of "the" or "this"',
    category: 'fricative (voiced)',
  },
  {
    id: 'core_uh',
    type: 'core',
    phoneme: 'uh',
    ipa: 'ʌ',
    exampleWords: ['cup', 'bus', 'sun'],
    soundPosition: 'Short U vowel, as in the middle of "cup" or "bus"',
    category: 'short vowel',
  },

  // ═══════════════════════════════════════
  // ONSET (20) — word-initial consonant sounds
  // ═══════════════════════════════════════
  {
    id: 'onset_bl',
    type: 'onset',
    phoneme: 'bl',
    ipa: 'bl',
    exampleWords: ['blue', 'black', 'block'],
    soundPosition: 'Consonant blend at the start of words like "blue" or "black"',
    category: 'initial blend',
  },
  {
    id: 'onset_dr',
    type: 'onset',
    phoneme: 'dr',
    ipa: 'dɹ',
    exampleWords: ['drum', 'draw', 'drop'],
    soundPosition: 'Consonant blend at the start of words like "drum" or "draw"',
    category: 'initial blend',
  },
  {
    id: 'onset_f',
    type: 'onset',
    phoneme: 'f',
    ipa: 'f',
    exampleWords: ['fan', 'fish', 'fun'],
    soundPosition: 'Voiceless labiodental fricative, as at the start of "fan" or "fish"',
    category: 'fricative',
  },
  {
    id: 'onset_fr',
    type: 'onset',
    phoneme: 'fr',
    ipa: 'fɹ',
    exampleWords: ['frog', 'from', 'free'],
    soundPosition: 'Consonant blend at the start of words like "frog" or "free"',
    category: 'initial blend',
  },
  {
    id: 'onset_gr',
    type: 'onset',
    phoneme: 'gr',
    ipa: 'gɹ',
    exampleWords: ['green', 'grab', 'grow'],
    soundPosition: 'Consonant blend at the start of words like "green" or "grab"',
    category: 'initial blend',
  },
  {
    id: 'onset_l',
    type: 'onset',
    phoneme: 'l',
    ipa: 'l',
    exampleWords: ['lip', 'leg', 'log'],
    soundPosition: 'Lateral approximant, as at the start of "lip" or "leg"',
    category: 'approximant',
  },
  {
    id: 'onset_m',
    type: 'onset',
    phoneme: 'm',
    ipa: 'm',
    exampleWords: ['map', 'mom', 'moon'],
    soundPosition: 'Bilabial nasal, as at the start of "map" or "mom"',
    category: 'nasal',
  },
  {
    id: 'onset_n',
    type: 'onset',
    phoneme: 'n',
    ipa: 'n',
    exampleWords: ['net', 'nap', 'nose'],
    soundPosition: 'Alveolar nasal, as at the start of "net" or "nap"',
    category: 'nasal',
  },
  {
    id: 'onset_r',
    type: 'onset',
    phoneme: 'r',
    ipa: 'ɹ',
    exampleWords: ['red', 'run', 'rain'],
    soundPosition: 'Alveolar approximant, as at the start of "red" or "run"',
    category: 'approximant',
  },
  {
    id: 'onset_s',
    type: 'onset',
    phoneme: 's',
    ipa: 's',
    exampleWords: ['sun', 'sit', 'sock'],
    soundPosition: 'Voiceless alveolar fricative, as at the start of "sun" or "sit"',
    category: 'fricative',
  },
  {
    id: 'onset_sh',
    type: 'onset',
    phoneme: 'sh',
    ipa: 'ʃ',
    exampleWords: ['ship', 'shop', 'shell'],
    soundPosition: 'Voiceless postalveolar fricative, as at the start of "ship" or "shop"',
    category: 'fricative',
  },
  {
    id: 'onset_sk',
    type: 'onset',
    phoneme: 'sk',
    ipa: 'sk',
    exampleWords: ['skip', 'skin', 'sky'],
    soundPosition: 'Consonant blend at the start of words like "skip" or "sky"',
    category: 'initial blend',
  },
  {
    id: 'onset_sm',
    type: 'onset',
    phoneme: 'sm',
    ipa: 'sm',
    exampleWords: ['smile', 'small', 'smoke'],
    soundPosition: 'Consonant blend at the start of words like "smile" or "small"',
    category: 'initial blend',
  },
  {
    id: 'onset_sn',
    type: 'onset',
    phoneme: 'sn',
    ipa: 'sn',
    exampleWords: ['snap', 'snail', 'snow'],
    soundPosition: 'Consonant blend at the start of words like "snap" or "snow"',
    category: 'initial blend',
  },
  {
    id: 'onset_st',
    type: 'onset',
    phoneme: 'st',
    ipa: 'st',
    exampleWords: ['stop', 'star', 'step'],
    soundPosition: 'Consonant blend at the start of words like "stop" or "star"',
    category: 'initial blend',
  },
  {
    id: 'onset_th',
    type: 'onset',
    phoneme: 'th',
    ipa: 'θ',
    exampleWords: ['thin', 'three', 'think'],
    soundPosition: 'Voiceless dental fricative, as at the start of "thin" or "three"',
    category: 'fricative',
  },
  {
    id: 'onset_v',
    type: 'onset',
    phoneme: 'v',
    ipa: 'v',
    exampleWords: ['van', 'vet', 'vine'],
    soundPosition: 'Voiced labiodental fricative, as at the start of "van" or "vet"',
    category: 'fricative',
  },
  {
    id: 'onset_w',
    type: 'onset',
    phoneme: 'w',
    ipa: 'w',
    exampleWords: ['web', 'win', 'wet'],
    soundPosition: 'Labio-velar approximant, as at the start of "web" or "win"',
    category: 'approximant',
  },
  {
    id: 'onset_wh',
    type: 'onset',
    phoneme: 'wh',
    ipa: 'w',
    exampleWords: ['when', 'what', 'white'],
    soundPosition: 'Labio-velar approximant (same as /w/ in General American), as at the start of "when" or "what"',
    category: 'approximant',
  },
  {
    id: 'onset_z',
    type: 'onset',
    phoneme: 'z',
    ipa: 'z',
    exampleWords: ['zip', 'zoo', 'zone'],
    soundPosition: 'Voiced alveolar fricative, as at the start of "zip" or "zoo"',
    category: 'fricative',
  },

  // ═══════════════════════════════════════
  // RIME (46) — word-ending syllable patterns
  // ═══════════════════════════════════════
  {
    id: 'rime_ade',
    type: 'rime',
    phoneme: '-ade',
    ipa: 'eɪd',
    exampleWords: ['made', 'shade', 'blade'],
    soundPosition: 'Rime pattern at the end of words like "made" or "shade"',
    category: 'long A rime',
  },
  {
    id: 'rime_ail',
    type: 'rime',
    phoneme: '-ail',
    ipa: 'eɪl',
    exampleWords: ['mail', 'tail', 'sail'],
    soundPosition: 'Rime pattern at the end of words like "mail" or "tail"',
    category: 'long A rime',
  },
  {
    id: 'rime_ain',
    type: 'rime',
    phoneme: '-ain',
    ipa: 'eɪn',
    exampleWords: ['rain', 'train', 'main'],
    soundPosition: 'Rime pattern at the end of words like "rain" or "train"',
    category: 'long A rime',
  },
  {
    id: 'rime_ait',
    type: 'rime',
    phoneme: '-ait',
    ipa: 'eɪt',
    exampleWords: ['wait', 'bait'],
    soundPosition: 'Rime pattern at the end of words like "wait" or "bait"',
    category: 'long A rime',
  },
  {
    id: 'rime_ake',
    type: 'rime',
    phoneme: '-ake',
    ipa: 'eɪk',
    exampleWords: ['cake', 'lake', 'make'],
    soundPosition: 'Rime pattern at the end of words like "cake" or "lake"',
    category: 'long A rime',
  },
  {
    id: 'rime_ang',
    type: 'rime',
    phoneme: '-ang',
    ipa: 'æŋ',
    exampleWords: ['bang', 'rang', 'sang'],
    soundPosition: 'Rime pattern at the end of words like "bang" or "rang"',
    category: 'short A rime',
  },
  {
    id: 'rime_ard',
    type: 'rime',
    phoneme: '-ard',
    ipa: 'ɑːɹd',
    exampleWords: ['card', 'hard', 'yard'],
    soundPosition: 'Rime pattern at the end of words like "card" or "hard"',
    category: 'r-controlled rime',
  },
  {
    id: 'rime_ark',
    type: 'rime',
    phoneme: '-ark',
    ipa: 'ɑːɹk',
    exampleWords: ['park', 'dark', 'bark'],
    soundPosition: 'Rime pattern at the end of words like "park" or "dark"',
    category: 'r-controlled rime',
  },
  {
    id: 'rime_arm',
    type: 'rime',
    phoneme: '-arm',
    ipa: 'ɑːɹm',
    exampleWords: ['farm', 'arm', 'harm'],
    soundPosition: 'Rime pattern at the end of words like "farm" or "arm"',
    category: 'r-controlled rime',
  },
  {
    id: 'rime_ase',
    type: 'rime',
    phoneme: '-ase',
    ipa: 'eɪs',
    exampleWords: ['case', 'base', 'chase'],
    soundPosition: 'Rime pattern at the end of words like "case" or "base"',
    category: 'long A rime',
  },
  {
    id: 'rime_ate',
    type: 'rime',
    phoneme: '-ate',
    ipa: 'eɪt',
    exampleWords: ['gate', 'late', 'plate'],
    soundPosition: 'Rime pattern at the end of words like "gate" or "late"',
    category: 'long A rime',
  },
  {
    id: 'rime_ave',
    type: 'rime',
    phoneme: '-ave',
    ipa: 'eɪv',
    exampleWords: ['cave', 'wave', 'brave'],
    soundPosition: 'Rime pattern at the end of words like "cave" or "wave"',
    category: 'long A rime',
  },
  {
    id: 'rime_ay',
    type: 'rime',
    phoneme: '-ay',
    ipa: 'eɪ',
    exampleWords: ['day', 'play', 'say'],
    soundPosition: 'Rime pattern at the end of words like "day" or "play"',
    category: 'long A rime',
  },
  {
    id: 'rime_eaf',
    type: 'rime',
    phoneme: '-eaf',
    ipa: 'iːf',
    exampleWords: ['leaf', 'deaf'],
    soundPosition: 'Rime pattern at the end of words like "leaf"',
    category: 'long E rime',
  },
  {
    id: 'rime_eam',
    type: 'rime',
    phoneme: '-eam',
    ipa: 'iːm',
    exampleWords: ['team', 'beam', 'dream'],
    soundPosition: 'Rime pattern at the end of words like "team" or "dream"',
    category: 'long E rime',
  },
  {
    id: 'rime_ean',
    type: 'rime',
    phoneme: '-ean',
    ipa: 'iːn',
    exampleWords: ['bean', 'clean', 'mean'],
    soundPosition: 'Rime pattern at the end of words like "bean" or "clean"',
    category: 'long E rime',
  },
  {
    id: 'rime_eat',
    type: 'rime',
    phoneme: '-eat',
    ipa: 'iːt',
    exampleWords: ['meat', 'seat', 'beat'],
    soundPosition: 'Rime pattern at the end of words like "meat" or "seat"',
    category: 'long E rime',
  },
  {
    id: 'rime_ee',
    type: 'rime',
    phoneme: '-ee',
    ipa: 'iː',
    exampleWords: ['bee', 'tree', 'free'],
    soundPosition: 'Rime pattern at the end of words like "bee" or "tree"',
    category: 'long E rime',
  },
  {
    id: 'rime_eef',
    type: 'rime',
    phoneme: '-eef',
    ipa: 'iːf',
    exampleWords: ['beef', 'reef'],
    soundPosition: 'Rime pattern at the end of words like "beef" or "reef"',
    category: 'long E rime',
  },
  {
    id: 'rime_eet',
    type: 'rime',
    phoneme: '-eet',
    ipa: 'iːt',
    exampleWords: ['feet', 'meet', 'sheet'],
    soundPosition: 'Rime pattern at the end of words like "feet" or "meet"',
    category: 'long E rime',
  },
  {
    id: 'rime_em',
    type: 'rime',
    phoneme: '-em',
    ipa: 'ɛm',
    exampleWords: ['gem', 'hem', 'stem'],
    soundPosition: 'Rime pattern at the end of words like "gem" or "hem"',
    category: 'short E rime',
  },
  {
    id: 'rime_ep',
    type: 'rime',
    phoneme: '-ep',
    ipa: 'ɛp',
    exampleWords: ['step', 'pep', 'rep'],
    soundPosition: 'Rime pattern at the end of words like "step" or "pep"',
    category: 'short E rime',
  },
  {
    id: 'rime_erk',
    type: 'rime',
    phoneme: '-erk',
    ipa: 'ɜːɹk',
    exampleWords: ['jerk', 'clerk', 'perk'],
    soundPosition: 'Rime pattern at the end of words like "jerk" or "perk"',
    category: 'r-controlled rime',
  },
  {
    id: 'rime_ib',
    type: 'rime',
    phoneme: '-ib',
    ipa: 'ɪb',
    exampleWords: ['bib', 'rib', 'crib'],
    soundPosition: 'Rime pattern at the end of words like "bib" or "rib"',
    category: 'short I rime',
  },
  {
    id: 'rime_ick',
    type: 'rime',
    phoneme: '-ick',
    ipa: 'ɪk',
    exampleWords: ['kick', 'pick', 'stick'],
    soundPosition: 'Rime pattern at the end of words like "kick" or "pick"',
    category: 'short I rime',
  },
  {
    id: 'rime_id',
    type: 'rime',
    phoneme: '-id',
    ipa: 'ɪd',
    exampleWords: ['kid', 'hid', 'lid'],
    soundPosition: 'Rime pattern at the end of words like "kid" or "hid"',
    category: 'short I rime',
  },
  {
    id: 'rime_ig',
    type: 'rime',
    phoneme: '-ig',
    ipa: 'ɪɡ',
    exampleWords: ['big', 'pig', 'dig'],
    soundPosition: 'Rime pattern at the end of words like "big" or "pig"',
    category: 'short I rime',
  },
  {
    id: 'rime_ip',
    type: 'rime',
    phoneme: '-ip',
    ipa: 'ɪp',
    exampleWords: ['lip', 'tip', 'ship'],
    soundPosition: 'Rime pattern at the end of words like "lip" or "tip"',
    category: 'short I rime',
  },
  {
    id: 'rime_ir',
    type: 'rime',
    phoneme: '-ir',
    ipa: 'ɜːɹ',
    exampleWords: ['sir', 'stir', 'fir'],
    soundPosition: 'Rime pattern at the end of words like "sir" or "stir"',
    category: 'r-controlled rime',
  },
  {
    id: 'rime_ird',
    type: 'rime',
    phoneme: '-ird',
    ipa: 'ɜːɹd',
    exampleWords: ['bird', 'third'],
    soundPosition: 'Rime pattern at the end of words like "bird" or "third"',
    category: 'r-controlled rime',
  },
  {
    id: 'rime_irst',
    type: 'rime',
    phoneme: '-irst',
    ipa: 'ɜːɹst',
    exampleWords: ['first', 'thirst'],
    soundPosition: 'Rime pattern at the end of words like "first" or "thirst"',
    category: 'r-controlled rime',
  },
  {
    id: 'rime_irt',
    type: 'rime',
    phoneme: '-irt',
    ipa: 'ɜːɹt',
    exampleWords: ['dirt', 'shirt', 'skirt'],
    soundPosition: 'Rime pattern at the end of words like "dirt" or "shirt"',
    category: 'r-controlled rime',
  },
  {
    id: 'rime_istle',
    type: 'rime',
    phoneme: '-istle',
    ipa: 'ɪsəl',
    exampleWords: ['whistle', 'thistle'],
    soundPosition: 'Rime pattern at the end of words like "whistle" or "thistle"',
    category: 'short I rime',
  },
  {
    id: 'rime_oad',
    type: 'rime',
    phoneme: '-oad',
    ipa: 'oʊd',
    exampleWords: ['road', 'toad', 'load'],
    soundPosition: 'Rime pattern at the end of words like "road" or "toad"',
    category: 'long O rime',
  },
  {
    id: 'rime_oap',
    type: 'rime',
    phoneme: '-oap',
    ipa: 'oʊp',
    exampleWords: ['soap'],
    soundPosition: 'Rime pattern at the end of the word "soap"',
    category: 'long O rime',
  },
  {
    id: 'rime_oil',
    type: 'rime',
    phoneme: '-oil',
    ipa: 'ɔɪl',
    exampleWords: ['oil', 'boil', 'soil'],
    soundPosition: 'Rime pattern at the end of words like "boil" or "soil"',
    category: 'diphthong rime',
  },
  {
    id: 'rime_oke',
    type: 'rime',
    phoneme: '-oke',
    ipa: 'oʊk',
    exampleWords: ['joke', 'woke', 'spoke'],
    soundPosition: 'Rime pattern at the end of words like "joke" or "spoke"',
    category: 'long O rime',
  },
  {
    id: 'rime_om',
    type: 'rime',
    phoneme: '-om',
    ipa: 'ɒm',
    exampleWords: ['mom', 'tom', 'from'],
    soundPosition: 'Rime pattern at the end of words like "mom" or "tom"',
    category: 'short O rime',
  },
  {
    id: 'rime_ool',
    type: 'rime',
    phoneme: '-ool',
    ipa: 'uːl',
    exampleWords: ['pool', 'cool', 'tool'],
    soundPosition: 'Rime pattern at the end of words like "pool" or "cool"',
    category: 'long OO rime',
  },
  {
    id: 'rime_oon',
    type: 'rime',
    phoneme: '-oon',
    ipa: 'uːn',
    exampleWords: ['moon', 'soon', 'spoon'],
    soundPosition: 'Rime pattern at the end of words like "moon" or "spoon"',
    category: 'long OO rime',
  },
  {
    id: 'rime_oor',
    type: 'rime',
    phoneme: '-oor',
    ipa: 'ɔːɹ',
    exampleWords: ['door', 'floor', 'poor'],
    soundPosition: 'Rime pattern at the end of words like "door" or "floor"',
    category: 'r-controlled rime',
  },
  {
    id: 'rime_oot',
    type: 'rime',
    phoneme: '-oot',
    ipa: 'uːt',
    exampleWords: ['boot', 'hoot', 'root'],
    soundPosition: 'Rime pattern at the end of words like "boot" or "root"',
    category: 'long OO rime',
  },
  {
    id: 'rime_ot',
    type: 'rime',
    phoneme: '-ot',
    ipa: 'ɒt',
    exampleWords: ['hot', 'pot', 'dot'],
    soundPosition: 'Rime pattern at the end of words like "hot" or "pot"',
    category: 'short O rime',
  },
  {
    id: 'rime_ub',
    type: 'rime',
    phoneme: '-ub',
    ipa: 'ʌb',
    exampleWords: ['tub', 'rub', 'club'],
    soundPosition: 'Rime pattern at the end of words like "tub" or "rub"',
    category: 'short U rime',
  },
  {
    id: 'rime_up',
    type: 'rime',
    phoneme: '-up',
    ipa: 'ʌp',
    exampleWords: ['cup', 'pup', 'up'],
    soundPosition: 'Rime pattern at the end of words like "cup" or "pup"',
    category: 'short U rime',
  },
  {
    id: 'rime_urse',
    type: 'rime',
    phoneme: '-urse',
    ipa: 'ɜːɹs',
    exampleWords: ['nurse', 'purse', 'curse'],
    soundPosition: 'Rime pattern at the end of words like "nurse" or "purse"',
    category: 'r-controlled rime',
  },
];
